services:
  programmarr:
    image: ghcr.io/alpinearchitecture/programmarr:latest
    # build: .   # uncomment for local testing
    container_name: programmarr
    restart: unless-stopped
    ports:
      - "7979:7979"
    volumes:
      - ./data:/data
    environment:
      - PROGRAMMARR_DATA=/data
      - PROGRAMMARR_SCRIPTS=/app
